#ifndef CZ_RVERSION_H
#define CZ_RVERSION_H

#define CZ_REAM_VERSION_MAJOR 0
#define CZ_REAM_VERSION_MINOR 1
#define CZ_REAM_VERSION_PATCH 0
#define CZ_REAM_VERSION_SERIAL ((CZ_REAM_VERSION_MAJOR << 16) | (CZ_REAM_VERSION_MINOR << 8) | CZ_REAM_VERSION_PATCH)

#endif // CZ_RVERSION_H
